name: Push to Espressif Component Service
on:
  workflow_run:
    workflows: ["ESP-IDF CI"]
    types: completed
jobs:
  upload_components:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master
      - name: Upload component to component registry
        uses: espressif/github-actions/upload_components@master
        with:
          name: "ConnectionHelper"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}