name: Push to Espressif Component Service
on:
  release:
    types: [created]
jobs:
  build_examples_for_verification:
    uses: ./.github/workflows/espidf.yaml

  upload_components:
    runs-on: ubuntu-latest
    needs: [build_examples_for_verification]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Remove unused examples and sources and arduino
        run: rm -rf arduino examples/arduino library.json library.properties

      - name: Upload component to component registry
        uses: espressif/upload-components-ci-action/@v1
        with:
          name: "ConnectionHelper"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}