name: ESP-IDF CI
on: [workflow_call, push]
jobs:
  esp_idf_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - name: v4_build
            version_number: v4.4.3
            target: esp32c3
          - name: v5_build
            version_number: v5.1.2
            target: esp32c6
        example:
          - name: simple

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.version.version_number }}
          target: ${{ matrix.version.target }}
          path: examples/espidf/${{ matrix.example.name }}